name: mi_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.2.0
  uuid: ^4.5.2
  go_router: ^17.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  permission_handler: ^11.3.1
  flutter_timezone: ^5.0.1
  share_plus: ^12.0.1
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  file_picker: ^10.3.10
  intl: ^0.19.0
  csv: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# --- CONFIGURACIÓN DE ICONOS DE LA APP ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/logagently.png"
  adaptive_icon_background: "#002d3f"
  adaptive_icon_foreground: "lib/assets/icon/logagently.png"

# --- CONFIGURACIÓN CORE DE FLUTTER ---
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/

flutter_native_splash:
  color: "#ffffff"
  # Eliminamos la línea de 'image' para que no cargue nada
  android_12:
    color: "#ffffff"
    # Al no poner imagen, Android mostrará el fondo limpio
  fullscreen: true